/* eslint-disable no-var */
/**
 * @see https://developer.ones.cn/docs/guide/advanced/storage
 * @summary ones.d.ts is generated by `op format` cli commands.
 * DO NOT MODIFY MANUALLY
 */
declare var ONESEntities: {
    bi_dashboard: {
        attributes: {
            dashboard_uuid?: string;
            team_uuid?: string;
            name?: string;
            owner_uuid?: string;
            status?: string;
            config_json?: string;
            cards_json?: string;
            created_by?: string;
            created_at?: number;
            updated_at?: number;
        };
        indexes: null;
    };
    bi_dataset: {
        attributes: {
            dataset_uuid?: string;
            team_uuid?: string;
            name?: string;
            source_type?: string;
            owner_uuid?: string;
            field_config_json?: string;
            base_filter_json?: string;
            description?: string;
            created_by?: string;
            created_at?: number;
            updated_at?: number;
        };
        indexes: null;
    };
    bi_audit_log: {
        attributes: {
            log_uuid?: string;
            team_uuid?: string;
            object_type?: string;
            object_uuid?: string;
            action?: string;
            operator_uuid?: string;
            detail_json?: string;
            created_at?: number;
        };
        indexes: null;
    };
    bi_app_config: {
        attributes: {
            config_key?: string;
            team_uuid?: string;
            config_json?: string;
            updated_by?: string;
            updated_at?: number;
        };
        indexes: null;
    };
    bi_report_snapshot: {
        attributes: {
            snapshot_uuid?: string;
            team_uuid?: string;
            dashboard_uuid?: string;
            card_uuid?: string;
            status?: string;
            data_json?: string;
            error?: string;
            created_by?: string;
            created_at?: number;
        };
        indexes: null;
    };
};
